name: Multiple Jobs

on:
  workflow_dispatch: 
    description: 'Test running 3 runners in parallel...'
    inputs:
      sleep1:
        description: 'job 1 duration'
        required: false
        default: '10'
      sleep2:
        description: 'job 2 duration'
        required: false
        default: '5'

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: sleep ${{ github.event.input.sleep1 }} && echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: sleep ${{ github.event.input.sleep2 }} && echo "::set-output name=test::bonjour"
      - id: step2
        run: echo "::set-output name=test::fromjob2"
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}} and ${{needs.job2.outputs.output1}} ${{needs.job2.outputs.output2}}
